---
name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.runforesightSecret }}
      - name: Checkout
        uses: actions/checkout@v3
